{{- if not .Values.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parcellab-sre-challenge.fullname" . }}
  labels:
    {{- include "parcellab-sre-challenge.labels" . | nindent 4 }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.dockerConfigJson }}
{{- end -}}
