name: Build, test and release app

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          fetch-depth: 0

      - uses: actions/setup-go@v5

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Run tests
        run: go test -v ./...

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}
          tags: |
            type=ref,event=branch
            type=sha,format=short,prefix=
            type=raw,value=latest
            type=raw,value=0.1.${{ env.GITHUB_RUN_NUMBER }}

      - name: Build docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
          
      - name: Load docker image into kind cluster
        run: |
          docker images
          kind get clusters
          kind load docker-image ${{ env.IMAGE_PREFIX }}:latest --name chart-testing

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (install)
        run: ct install --all
