name: Deploy app

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      salutation:
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write
  security-events: write

jobs:
  deploy:
    name: Deploy app
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:  
          fetch-depth: 0
      
      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install unzip

      - name: Set up Helm
        uses: azure/setup-helm@v3
      
      - name: Add helm charts repo
        run: |
          helm repo add ${{ github.event.repository.name }} https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          helm repo update
      
      - name: Create registry secret base64 content
        id: create-registry-secret
        run: |
          AUTH=$(echo -n ${{ secrets.GITHUB_TOKEN }} | base64 -w 0)
          DOCKER_CONFIG_JSON='{"auths":{"https://ghcr.io":{"username":"${{ github.repository_owner }}","password":"${{ secrets.GITHUB_TOKEN }}","auth":"'$AUTH'"}}}'
          DOCKER_CONFIG_JSON_BASE64=$(echo -n $DOCKER_CONFIG_JSON | base64 -w 0)
          echo "DOCKER_CONFIG_JSON_BASE64=$DOCKER_CONFIG_JSON_BASE64" >> "$GITHUB_OUTPUT"
      
      - name: Install/Upgrade helm chart
        env:
          DOCKER_CONFIG_JSON_BASE64: ${{ steps.create-registry-secret.outputs.DOCKER_CONFIG_JSON_BASE64 }}
        run: helm upgrade -i ${{ inputs.environment }} -n ${{ inputs.environment }} ${{ github.event.repository.name }}/${{ github.event.repository.name }} --set image.tag=${{ inputs.tag }} --set dockerConfigJson=$DOCKER_CONFIG_JSON_BASE64 --set env.SALUTATION=${{ inputs.salutation }}
