name: Deploy app

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}

permissions:
  contents: write
  packages: write
  id-token: write
  security-events: write

jobs:
  deploy:
    name: Deploy app
    runs-on: arc-runner-set
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.parcellab.demo.riffies.com
    steps:
      - uses: actions/checkout@v4
        with:  
          fetch-depth: 0
      
      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install unzip

      - name: Set up Helm
        uses: azure/setup-helm@v4
      
      - name: Add helm charts repo
        run: |
          helm repo add ${{ github.event.repository.name }} https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          helm repo update
      
      - name: Create registry secret base64 content
        id: create-registry-secret
        run: |
          AUTH=$(echo -n ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} | base64 -w 0)
          DOCKER_CONFIG_JSON='{"auths":{"https://ghcr.io":{"username":"${{ github.repository_owner }}","password":"${{ secrets.GITHUB_TOKEN }}","auth":"'$AUTH'"}}}'
          DOCKER_CONFIG_JSON_BASE64=$(echo -n $DOCKER_CONFIG_JSON | base64 -w 0)
          echo "::add-mask::$DOCKER_CONFIG_JSON_BASE64"
          echo "DOCKER_CONFIG_JSON_BASE64=$DOCKER_CONFIG_JSON_BASE64" >> "$GITHUB_OUTPUT"
      
      - name: Install/Upgrade helm chart
        env:
          DOCKER_CONFIG_JSON_BASE64: ${{ steps.create-registry-secret.outputs.DOCKER_CONFIG_JSON_BASE64 }}
        run: helm upgrade --atomic --wait -i ${{ inputs.environment }} ${{ github.event.repository.name }}/${{ github.event.repository.name }} -n ${{ inputs.environment }} -f env/${{ inputs.environment }}.yaml --set image.tag=${GITHUB_SHA::7} --set dockerConfigJson=${{ env.DOCKER_CONFIG_JSON_BASE64 }}
