name: Deploy app

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.parcellab.demo.riffies.com
    steps:
      - uses: actions/checkout@v4
        with:  
          fetch-depth: 0
      
      - uses: grafana/k6-action@v0.3.1
        with:
          filename: loadtest.js
          flags:  --vus 100 --duration 1m --summary-export ${{ inputs.environment }}-results.json
        env:
          HOST: ${{ inputs.environment }}.parcellab.demo.riffies.com
      

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}-results.json
          path: ${{ inputs.environment }}-results.json
